objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>Expense-{000}</displayFormat>
        <label>Expense Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ExpenseOfMember__c.object
<CustomObject>
    <fields>
        <fullName>AmountOfContribution__c</fullName>
        <label>AmountOfContribution</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Id__c</fullName>
        <label>Email_Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ExpenseId__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>ExpenseOfMembers</relationshipLabel>
        <relationshipName>ExpenseOfMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MemberId__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>ExpenseOfMembers</relationshipLabel>
        <relationshipName>ExpenseOfMembers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ExpenseOfMember</label>
    <nameField>
        <displayFormat>EOM-{0000}</displayFormat>
        <label>ExpenseOfMember Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExpenseOfMembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email_Id__c</fullName>
        <label>Email_Id</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>Member-{000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExpenseTest.cls
@isTest

public class ExpenseTest {
 public testMethod static void myTest(){
      
        Expense__c expense = new Expense__c();
        expense.Amount__c=10000;
        expense.Event__c='party';
        insert expense;
        Member__c member = new Member__c();
        member.FirstName__c='abc';
        member.LastName__c='xyz';
        member.Email_Id__c='abc@abc.com';
        insert member;
        ExpenseOfMember__c expmem = new ExpenseOfMember__c();
        expmem.MemberId__c=member.Id;
        expmem.ExpenseId__c=expense.Id;
        expmem.AmountOfContribution__c=5000;
        insert expmem;
        ExpenseMemberExtension expEXT= new ExpenseMemberExtension(new ApexPages.StandardController(expense));
        
        List<ExpenseOfMember__c> ge = new List<ExpenseOfMember__c>();
        ge = expExt.getExpeseAndMembers();
        
}
}