objects/Expense__c.object
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>Expense-{000}</displayFormat>
        <label>Expense Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ExpenseOfMember__c.object
<CustomObject>
    <fields>
        <fullName>AmountOfContribution__c</fullName>
        <label>AmountOfContribution</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpenseId__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>ExpenseOfMembers</relationshipLabel>
        <relationshipName>ExpenseOfMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MemberId__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>ExpenseOfMembers</relationshipLabel>
        <relationshipName>ExpenseOfMembers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ExpenseOfMember</label>
    <nameField>
        <displayFormat>EOM-{0000}</displayFormat>
        <label>ExpenseOfMember Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExpenseOfMembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>Member-{000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExpenseMemberExtension.cls
public class ExpenseMemberExtension {

    public Expense__c expense{get;set;}
    public List<ExpenseOfMember__c> expenseMember{get;set;}

    public ExpenseMemberExtension(ApexPages.StandardController controller) {
        expense = (Expense__c)controller.getRecord();
        expenseMember = getExpeseAndMembers();
    }
    
    public List<ExpenseOfMember__c> getExpeseAndMembers(){
        return [Select AmountOfContribution__c,MemberId__r.FirstName__c from ExpenseOfMember__c where   ExpenseId__c =: expense.Id];
    }

}